services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - webpack
  webpack:
    image: node:16 # Use an official Node.js image
    working_dir: /app
    command: ["npm", "run", "dev"] # This should match your npm script for Webpack
    volumes:
      - ./app:/app
    ports:
      - "8080:8080" # Adjust if needed, e.g., Webpack Dev Server default port
